//--------------------------------------------------------------------------------------
// Generated by ExcelMacro From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// バフ、デバフ種別データ
	/// </summary>
	[Serializable]
	public partial class EffectTypeDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// EffectTypeData の配列データ。
		/// </summary>
		public EffectTypeData[] data;

		/// <summary>
		/// アクセスユーティリティ: SelectTypeid（キーで EffectTypeData[] を引けます）。
		/// </summary>
		public Dictionary<int, EffectTypeData> SelectTypeid { get; private set; }

		public void OnBeforeSerialize()
		{
		}
		public void OnAfterDeserialize()
		{
			SelectTypeid = data.Select(x => x.TypeId).Distinct().ToDictionary(key => key, val => data.First(x => x.TypeId == val));
		}
	}
	
	/// <summary>
	/// バフ、デバフ種別のデータモデル
	/// </summary>
	[Serializable]
	public partial class EffectTypeData
	{
		/// <summary>
		/// 種類
		/// </summary>
		public int TypeId;
		/// <summary>
		/// 説明 {0}:ノード {1}:数 {2}:素材
		/// </summary>
		public string Description;
		/// <summary>
		/// 評価パターン
		/// </summary>
		public int Evaluation;
		/// <summary>
		/// 付加時のタイプ（1:Input 2:Output 3:TextOnly 100:Eternal）
		/// </summary>
		public int ViewType;

		public EffectTypeData Clone()
		{
			return (EffectTypeData) MemberwiseClone();
		}
	}
}
