//--------------------------------------------------------------------------------------
// Generated by ExcelMacro From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// バフ、デバフデータ
	/// </summary>
	[Serializable]
	public partial class EffectDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// EffectData の配列データ。
		/// </summary>
		public EffectData[] data;

		/// <summary>
		/// アクセスユーティリティ: SelectId（キーで EffectData[] を引けます）。
		/// </summary>
		public Dictionary<int, EffectData> SelectId { get; private set; }

		public void OnBeforeSerialize()
		{
		}
		public void OnAfterDeserialize()
		{
			SelectId = data.Select(x => x.Id).Distinct().ToDictionary(key => key, val => data.First(x => x.Id == val));
		}
	}
	
	/// <summary>
	/// バフ、デバフのデータモデル
	/// </summary>
	[Serializable]
	public partial class EffectData
	{
		/// <summary>
		/// ID
		/// </summary>
		public int Id;
		/// <summary>
		/// 名前
		/// </summary>
		public string DisplayName;
		/// <summary>
		/// 種類
		/// </summary>
		public int Type;
		/// <summary>
		/// 効果値{1}
		/// </summary>
		public int Value;
		/// <summary>
		/// 効果時間{3}
		/// </summary>
		public int Duration;
		/// <summary>
		/// 対象ノード
		/// </summary>
		public int[] TargetNodes;
		/// <summary>
		/// 対象資源
		/// </summary>
		public int[] TargetResources;

		public EffectData Clone()
		{
			return (EffectData) MemberwiseClone();
		}
	}
}
