//--------------------------------------------------------------------------------------
// Generated by ExcelToPython From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// ノードコストデータ
	/// </summary>
	[Serializable]
	public partial class NodeCostDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// NodeCostData の配列データ。
		/// </summary>
		public NodeCostData[] data;


		/// <summary>
		/// アクセスユーティリティ: SelectId（キーで NodeCostData[] を引けます）。
		/// </summary>

		public Dictionary<int, NodeCostData[]> SelectId { get; private set; }



		public void OnBeforeSerialize()
		{
		}

		public void OnAfterDeserialize()
		{

			SelectId = data.Select(x => x.Id).Distinct().ToDictionary(key => key, val => data.Where(x => x.Id == val).ToArray());

		}

	}

	/// <summary>
	/// ノードコストのデータモデル
	/// </summary>
	[Serializable]
	public partial class NodeCostData
	{

		/// <summary>
		/// ID
		/// </summary>
		public int Id;

		/// <summary>
		/// 生成数
		/// </summary>
		public int Count;

		/// <summary>
		/// 生成コスト（0は制作不可）
		/// </summary>
		public int Cost;


		public NodeCostData Clone()
		{
			return (NodeCostData) MemberwiseClone();
		}
	}

}