//--------------------------------------------------------------------------------------
// Generated by ExcelToPython From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// 依頼主データ
	/// </summary>
	[Serializable]
	public partial class RequestClientDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// RequestClientData の配列データ。
		/// </summary>
		public RequestClientData[] data;


		/// <summary>
		/// アクセスユーティリティ: SelectId（キーで RequestClientData を引けます）。
		/// </summary>

		public Dictionary<int, RequestClientData> SelectId { get; private set; }



		public void OnBeforeSerialize()
		{
		}

		public void OnAfterDeserialize()
		{

			SelectId = data.Select(x => x.Id).Distinct().ToDictionary(key => key, val => data.First(x => x.Id == val));

		}

	}

	/// <summary>
	/// 依頼主のデータモデル
	/// </summary>
	[Serializable]
	public partial class RequestClientData
	{

		/// <summary>
		/// ID
		/// </summary>
		public int Id;

		/// <summary>
		/// 名前
		/// </summary>
		public string DisplayName;


		public RequestClientData Clone()
		{
			return (RequestClientData) MemberwiseClone();
		}
	}

}