//------------------------------------------------------------------------------
// Generated by ExcelMacro From データ.xlsm
//------------------------------------------------------------------------------

namespace Define
{
	public class NodeId
	{
		public const int 水処理ユニット = 1;
		public const int 発電ユニット = 2;
		public const int 農業モジュール = 3;
		public const int 居住モジュール = 4;
		public const int リソースバッファ = 5;
		public const int 工場モジュール = 6;
		public const int 商業モジュール = 7;
		public const int 治安維持ユニット = 8;
		public const int 瓦礫 = 9;
		public const int 食品加工モジュール = 10;
	}
}
