//--------------------------------------------------------------------------------------
// Generated by ExcelToPython From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// 章データ
	/// </summary>
	[Serializable]
	public partial class ChapterDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// ChapterData の配列データ。
		/// </summary>
		public ChapterData[] data;


		/// <summary>
		/// アクセスユーティリティ: SelectChapterAndSection（キーで ChapterData を引けます）。
		/// </summary>

		public Dictionary<string, ChapterData> SelectChapterAndSection { get; private set; }



		public void OnBeforeSerialize()
		{
		}

		public void OnAfterDeserialize()
		{

			SelectChapterAndSection = data.Select(x => string.Format("{0}_{1}", x.Chapter, x.Section)).Distinct().ToDictionary(key => key, val => data.First(x => x.Chapter == int.Parse(val.Split('_')[0]) && x.Section == int.Parse(val.Split('_')[1])));

		}

	}

	/// <summary>
	/// 章のデータモデル
	/// </summary>
	[Serializable]
	public partial class ChapterData
	{

		/// <summary>
		/// 章
		/// </summary>
		public int Chapter;

		/// <summary>
		/// 節
		/// </summary>
		public int Section;

		/// <summary>
		/// 詳細
		/// </summary>
		public string Description;

		/// <summary>
		/// DemoID
		/// </summary>
		public int DemoId;


		public ChapterData Clone()
		{
			return (ChapterData) MemberwiseClone();
		}
	}

}