//--------------------------------------------------------------------------------------
// Generated by ExcelToPython From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// デモデータ
	/// </summary>
	[Serializable]
	public partial class DemoDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// DemoData の配列データ。
		/// </summary>
		public DemoData[] data;


		/// <summary>
		/// アクセスユーティリティ: SelectId（キーで DemoData[] を引けます）。
		/// </summary>

		public Dictionary<int, DemoData[]> SelectId { get; private set; }



		public void OnBeforeSerialize()
		{
		}

		public void OnAfterDeserialize()
		{

			SelectId = data.Select(x => x.Id).Distinct().ToDictionary(key => key, val => data.Where(x => x.Id == val).ToArray());

		}

	}

	/// <summary>
	/// デモのデータモデル
	/// </summary>
	[Serializable]
	public partial class DemoData
	{

		/// <summary>
		/// ID
		/// </summary>
		public int Id;

		/// <summary>
		/// 名前
		/// </summary>
		public string Type;

		/// <summary>
		/// 名前
		/// </summary>
		public string Parameter;

		/// <summary>
		/// 位置（x,y:座標、z:管理ID）
		/// </summary>
		public Vector3 Postion;


		public DemoData Clone()
		{
			return (DemoData) MemberwiseClone();
		}
	}

}