//------------------------------------------------------------------------------
// Generated by ExcelMacro From データ.xlsm
//------------------------------------------------------------------------------

namespace Define
{
	public class EffectId
	{
		public const int なし = 1;
		public const int 瓦礫の除去 = 2;
		public const int 居住モジュール開放 = 3;
		public const int 工業モジュール開放 = 4;
		public const int 商業モジュール開放 = 5;
		public const int 食品加工モジュール開放 = 6;
		public const int 農業モジュール開放 = 7;
		public const int テスト = 8;
		public const int テスト2 = 9;
	}
}
