//--------------------------------------------------------------------------------------
// Generated by ExcelToPython From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// ノードデータ
	/// </summary>
	[Serializable]
	public partial class NodeDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// NodeData の配列データ。
		/// </summary>
		public NodeData[] data;


		/// <summary>
		/// アクセスユーティリティ: SelectId（キーで NodeData を引けます）。
		/// </summary>

		public Dictionary<int, NodeData> SelectId { get; private set; }



		public void OnBeforeSerialize()
		{
		}

		public void OnAfterDeserialize()
		{

			SelectId = data.Select(x => x.Id).Distinct().ToDictionary(key => key, val => data.First(x => x.Id == val));

		}

	}

	/// <summary>
	/// ノードのデータモデル
	/// </summary>
	[Serializable]
	public partial class NodeData
	{

		/// <summary>
		/// ID
		/// </summary>
		public int Id;

		/// <summary>
		/// 名前
		/// </summary>
		public string DisplayName;

		/// <summary>
		/// 解放する章
		/// </summary>
		public int UnlockChapter;

		/// <summary>
		/// 解放する節
		/// </summary>
		public int UnlockSection;

		/// <summary>
		/// モジュールか
		/// </summary>
		public bool IsModule;


		public NodeData Clone()
		{
			return (NodeData) MemberwiseClone();
		}
	}

}