//--------------------------------------------------------------------------------------
// Generated by ExcelMacro From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// ノードIOデータ
	/// </summary>
	[Serializable]
	public partial class NodeIoDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// NodeIoData の配列データ。
		/// </summary>
		public NodeIoData[] data;

		/// <summary>
		/// アクセスユーティリティ: SelectId（キーで NodeIoData[] を引けます）。
		/// </summary>
		public Dictionary<int, NodeIoData[]> SelectId { get; private set; }

		public void OnBeforeSerialize()
		{
		}
		public void OnAfterDeserialize()
		{
			SelectId = data.Select(x => x.Id).Distinct().ToDictionary(key => key, val => data.Where(x => x.Id == val).ToArray());
		}
	}
	
	/// <summary>
	/// ノードIOのデータモデル
	/// </summary>
	[Serializable]
	public partial class NodeIoData
	{
		/// <summary>
		/// ID
		/// </summary>
		public int Id;
		/// <summary>
		/// レベル
		/// </summary>
		public int Level;
		/// <summary>
		/// 出力にかかる時間(ms）
		/// </summary>
		public int OutputSec;
		/// <summary>
		/// 入力リソース
		/// </summary>
		public int[] InputResourceTypes;
		/// <summary>
		/// 入力量
		/// </summary>
		public int[] InputValues;
		/// <summary>
		/// 出力リソース
		/// </summary>
		public int[] OutputResourceTypes;
		/// <summary>
		/// 出力量
		/// </summary>
		public int[] OutputValues;

		public NodeIoData Clone()
		{
			return (NodeIoData) MemberwiseClone();
		}
	}
}
