//--------------------------------------------------------------------------------------
// Generated by ExcelMacro From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// 依頼種別データ
	/// </summary>
	[Serializable]
	public partial class RequestTypeDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// RequestTypeData の配列データ。
		/// </summary>
		public RequestTypeData[] data;

		/// <summary>
		/// アクセスユーティリティ: SelectId（キーで RequestTypeData[] を引けます）。
		/// </summary>
		public Dictionary<int, RequestTypeData> SelectId { get; private set; }

		public void OnBeforeSerialize()
		{
		}
		public void OnAfterDeserialize()
		{
			SelectId = data.Select(x => x.Id).Distinct().ToDictionary(key => key, val => data.First(x => x.Id == val));
		}
	}
	
	/// <summary>
	/// 依頼種別のデータモデル
	/// </summary>
	[Serializable]
	public partial class RequestTypeData
	{
		/// <summary>
		/// ID
		/// </summary>
		public int Id;
		/// <summary>
		/// 説明
		/// </summary>
		public string Description;

		public RequestTypeData Clone()
		{
			return (RequestTypeData) MemberwiseClone();
		}
	}
}
