//--------------------------------------------------------------------------------------
// Generated by ExcelToPython From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// 依頼データ
	/// </summary>
	[Serializable]
	public partial class RequestDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// RequestData の配列データ。
		/// </summary>
		public RequestData[] data;


		/// <summary>
		/// アクセスユーティリティ: SelectChapterAndSection（キーで RequestData[] を引けます）。
		/// </summary>

		public Dictionary<string, RequestData[]> SelectChapterAndSection { get; private set; }



		public void OnBeforeSerialize()
		{
		}

		public void OnAfterDeserialize()
		{

			SelectChapterAndSection = data.Select(x => string.Format("{0}_{1}", x.Chapter, x.Section)).Distinct().ToDictionary(key => key, val => data.Where(x => x.Chapter == int.Parse(val.Split('_')[0]) && x.Section == int.Parse(val.Split('_')[1])).ToArray());

		}

	}

	/// <summary>
	/// 依頼のデータモデル
	/// </summary>
	[Serializable]
	public partial class RequestData
	{

		/// <summary>
		/// 章
		/// </summary>
		public int Chapter;

		/// <summary>
		/// 節
		/// </summary>
		public int Section;

		/// <summary>
		/// タイトル
		/// </summary>
		public string DisplayTitle;

		/// <summary>
		/// 詳細
		/// </summary>
		public string Description;

		/// <summary>
		/// AIセリフ
		/// </summary>
		public string Message;

		/// <summary>
		/// 対立する依頼
		/// </summary>
		public int ConflictIds;

		/// <summary>
		/// 依頼者の顔ID
		/// </summary>
		public int FaceID;

		/// <summary>
		/// 数{1}
		/// </summary>
		public int Num;

		/// <summary>
		/// レベル{2}
		/// </summary>
		public int Level;

		/// <summary>
		/// 依頼種別
		/// </summary>
		public int Type;

		/// <summary>
		/// 対象ノード{0}
		/// </summary>
		public int[] TargetNodes;

		/// <summary>
		/// 成功特典
		/// </summary>
		public int SuccesedEffect;

		/// <summary>
		/// 失敗ペナルティ
		/// </summary>
		public int FailedEffect;


		public RequestData Clone()
		{
			return (RequestData) MemberwiseClone();
		}
	}

}