//--------------------------------------------------------------------------------------
// Generated by ExcelMacro From データ.xlsm
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Data.Master
{
	/// <summary>
	/// 素材データ
	/// </summary>
	[Serializable]
	public partial class ResourceDatas : ISerializationCallbackReceiver
	{
		/// <summary>
		/// ResourceData の配列データ。
		/// </summary>
		public ResourceData[] data;

		/// <summary>
		/// アクセスユーティリティ: SelectId（キーで ResourceData[] を引けます）。
		/// </summary>
		public Dictionary<int, ResourceData> SelectId { get; private set; }

		public void OnBeforeSerialize()
		{
		}
		public void OnAfterDeserialize()
		{
			SelectId = data.Select(x => x.Id).Distinct().ToDictionary(key => key, val => data.First(x => x.Id == val));
		}
	}
	
	/// <summary>
	/// 素材のデータモデル
	/// </summary>
	[Serializable]
	public partial class ResourceData
	{
		/// <summary>
		/// ID
		/// </summary>
		public int Id;
		/// <summary>
		/// 名前
		/// </summary>
		public string DisplayName;
		/// <summary>
		/// 売り物か
		/// </summary>
		public bool Salable;
		/// <summary>
		/// 色
		/// </summary>
		public Color Color;

		public ResourceData Clone()
		{
			return (ResourceData) MemberwiseClone();
		}
	}
}
