//------------------------------------------------------------------------------
// Generated by ExcelMacro From データ.xlsm
//------------------------------------------------------------------------------

namespace Define
{
	public class ResourceId
	{
		public const int 全て = 0;
		public const int 資金 = 1;
		public const int 水 = 2;
		public const int 電気 = 3;
		public const int 食料 = 4;
		public const int 労働力 = 5;
		public const int 商品 = 6;
		public const int 安全 = 7;
	}
}
